# configs/LSTM.yaml

# 模型参数
model_name: 'LSTM'
img_size: 224
num_classes: 1


datasets:
  path: 'datasets'
  train: 
    - 'train_data.csv'
  test: 
    - 'test_data.csv'


batch_size: 16


# 训练参数
num_epochs: 500
learning_rate: 0.001
model_save_dir: './results/LSTM'

# EarlyStopping 参数
patience: 50
delta: 0.005

load_mode: 3

loss: 'mse' 



# loss_weights: '0.7,0.3'